name: steerable_pdo_experiments
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.20.1
  - pip=20.3.3
  - python=3.7.9
  - pytorch=1.8.0
  - cudatoolkit=10.2
  - scikit-image=0.18.1
  - scipy=1.6.1
  - sympy
  - torchvision=0.9.0
  - pip:
    - hydra-core==1.0.6
    - pytorch-lightning==1.2.0
    - sparse==0.12.0
    - torchmetrics=0.2.0
    - cython
    - pyyaml
